In [5]:
## Create array using numpy
!pip install numpy
import numpy as np
arr = np.array([1,2,2,3,3,3])
print(arr)
print(type(arr))

  Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl (12.8 MB)
[1 2 2 3 3 3]
<class 'numpy.ndarray'>


In [6]:
print(arr.shape)

(6,)


In [9]:
arr1 = np.asarray([1,2,3])
print(arr1)
print(arr1.size)

[1 2 3]
3


In [12]:
## Reshaping

new_reshape = np.array([[1,2,3],[4,5,6]])
new_shape = new_reshape.reshape(3,2)
print(new_shape)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
## Identity matrix

iden = np.eye(2)
print(iden)

[[1. 0.]
 [0. 1.]]
