In [5]:
## Create array using numpy
!pip install numpy
import numpy as np
arr = np.array([1,2,2,3,3,3])
print(arr)
print(type(arr))

  Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.2-cp312-cp312-win_amd64.whl (12.8 MB)
[1 2 2 3 3 3]
<class 'numpy.ndarray'>


In [6]:
## !pip install numpy

import numpy as np
arr = np.array([1,2,3,4])
print(arr.shape)

(4,)


In [9]:
arr1 = np.asarray([1,2,3])
print(arr1)
print(arr1.size)

[1 2 3]
3


In [12]:
## Reshaping

new_reshape = np.array([[1,2,3],[4,5,6]])
new_shape = new_reshape.reshape(3,2)
print(new_shape)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
## Identity matrix

iden = np.eye(2)
print(iden)

[[1. 0.]
 [0. 1.]]


In [5]:
## Operation
new_num = np.array([1,2,3,4,5])
print(np.ndim(new_num))

1


In [ ]:
arr1= np.array([1,2,3,4])
arr2= np.array([5,6,7,8])

## Element wise simple mathematical opeartion
print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [10]:
print(arr1)
print(arr2)

[1 2 3 4]
[5 6 7 8]


In [12]:
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))
print(np.var(arr1))

2.5
2.5
1.118033988749895
1.25


In [14]:
## Normalization

## normalized = (data -mean)/std

Normalized_data = (arr1-np.mean(arr1))/np.std(arr1)
print(Normalized_data)

[-1.34164079 -0.4472136   0.4472136   1.34164079]
