## Ravel

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6])
print(type(arr.ravel()))

<class 'numpy.ndarray'>


In [7]:
arr = np.array([[1,2,3,4,5,6],[7,8,9,1,2,3]])
print((arr.ravel()))

[1 2 3 4 5 6 7 8 9 1 2 3]


In [9]:
a_ravel = arr.ravel()
print(a_ravel)
print(id(arr))
print(id(arr.ravel()))
print(id(a_ravel))


[1 2 3 4 5 6 7 8 9 1 2 3]
1814601056048
1814601048848
1814601041264


In [10]:
# .__array_interface__['data'][0]

# Attribute gives you the actual address where the raw array data begins


In [14]:
print(f"Data address of arr: {arr.__array_interface__['data'][0]}")

Data address of arr: 1814438500976


In [15]:
print(f"Data address of arr.ravel(): {arr.ravel().__array_interface__['data'][0]}")

Data address of arr.ravel(): 1814438500976


In [16]:
print(f"Data address of a_ravel: {a_ravel.__array_interface__['data'][0]}")

Data address of a_ravel: 1814438500976


## flatten()

Flatten into 1D (returns a copy)

In [17]:
b = arr.flatten()

In [19]:
print(f"Data address of b: {arr.__array_interface__['data'][0]}")
print(f"Data address of b: {b.__array_interface__['data'][0]}")

Data address of b: 1814438500976
Data address of b: 1814438495264


## Resize 

Resize Array In-place

nlike reshape(), it can change total size. Data may be truncated or padded with zeroes.

In [21]:
a = np.array([[1,2,3],[4,5,6]])


In [23]:
a = a.reshape(3,-1)

In [24]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a = np.array([[1,2,3],[4,5,6]])


In [26]:
a.resize((3,3))

In [27]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

## squeeze()

Remove single-dimension axes

Useful for removing extra dimensions from image or model output shape like (1,28,28,1)

In [28]:
a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [29]:
b = np.squeeze(a)

In [30]:
b

array([1, 2, 3])