## AGENDA 

##### NUMPY

Pyhton lists are:
    - Flexible but slower numerical operation
    - Not designed for matrix math or
    - Does not support vectorized operation
    - Are memory inefficient for large numerical data

Why use numpy?
    - Fast than pure python for numerical computational
    - Vectorized operation (no explicit loops)
    - Broadcasting (operate on arrays of different shape)
    - Memory efficient
    - Comes with powerful linear algebra, random tools etc

Use of numpy:
    - Scientific python


In [2]:
import numpy as np

### Creating arays in numpy

### 1. np.array()

In [3]:
arr_1 = np.array([1,2,3])
arr_1 = np.array([1,2,3])
arr_1 = np.array([1,2,3])

In [6]:
print(arr_1)
print(type (arr_1))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
arr_2 = np.array([1,2,3,"Hello"])
print(arr_2)

['1' '2' '3' 'Hello']


In [9]:
arr_3 = np.array([1,2,3], dtype=np.float16())
print(arr_3)

[1. 2. 3.]


## 2. np.arange(start, stop, step)

In [10]:
b = np.arange(1, 11, 2)

In [11]:
b

array([1, 3, 5, 7, 9])

## np.linspace(start, stop, num=x)

#### stop - inclusive

In [12]:
np_linspace_1 = np.linspace(1, 100, 4)
print(np_linspace_1)

[  1.  34.  67. 100.]


In [14]:
np_linspace_2 = np.linspace(1, 10, 10)
print(np_linspace_2)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [15]:
for num in np.linspace(1, 10, 10):
    print(num)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


### 4. np.zeroes(shape)
##### shape - shape of matrix

In [16]:
npz_1 = np.zeros(5)
print(npz_1)

[0. 0. 0. 0. 0.]


In [17]:
npz_2 = np.zeros((5,5))
print(npz_2)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
npz_3 = np.zeros((5,5,5))
print(npz_3)



[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [19]:
npz_3.ndim

3

## 5. np.ones(shape)
#### shape - shape of matrix

In [20]:
npo_1 = np.ones((2,3))
print(npo_1)

[[1. 1. 1.]
 [1. 1. 1.]]


## 6. np.full(shape, fill_value)

In [21]:
npf_1 = np.full((2,3), 10)
print(npf_1)

[[10 10 10]
 [10 10 10]]


## 7. np.eye(shape)
- Doesnot exist in 1D
- min of D, shape

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [25]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## 8. np.empty(shape)

In [26]:
np.empty((2,3),dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0]], dtype=int8)

## 9. np.random.rand(shape)
##### random values between 0 and 1
##### ML weights random initialization

In [27]:
np.random.rand(2,8)

array([[0.50648115, 0.07028795, 0.65941372, 0.5953626 , 0.90843289,
        0.01640569, 0.05921738, 0.4842206 ],
       [0.69464679, 0.91882976, 0.11353633, 0.93375884, 0.75825823,
        0.57232655, 0.27496967, 0.67935713]])

## Numpy Array Attribites
### 1. ndaray.shape

In [28]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### 2. nd.array.ndim

In [1]:
print(arr.ndim)

NameError: name 'arr' is not defined

### 3. nd.array.size

In [30]:
print(arr.size)

6


### 4. ndarray.dtyper

In [31]:
print(arr.dtype)

int64


### 5. ndarray.itemsize
##### Returns the size in bytes of one elements.

1 bytes --> 8 bit

int8 --> 8 bit

int64 --> int8*8 --> int64

In [32]:
print(arr.itemsize)

8


### ndarray.nbytes

Total number of bytes consumed by the array

In [33]:
print(arr.nbytes)

48


### 7. nd.array.T
Returns the tranpose of the array

In [34]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


## Array Reshaping and resizing in numpy

### 1. Reshape()

### Change shape without changing Data

### Notes:

The Total number of elements must remain the same.

Reshape() returns a new view if possible (no copy).

You can use -1 to let numpy infer one dimension:

In [38]:
arr = np.array([1,2,3,4,5,6])   ## Vector
print(arr.shape)

(6,)


In [40]:
reshaped_1 = arr.reshape(2,3)
print(reshaped_1)

[[1 2 3]
 [4 5 6]]


In [45]:
reshaped_2 = arr.reshape(3,2)
print(reshaped_2)

[[1 2]
 [3 4]
 [5 6]]


In [47]:
reshaped_3 = arr.reshape(1,6)
print(reshaped_3)
print(reshaped_3.ndim)

[[1 2 3 4 5 6]]
2


In [3]:
arr = np.array([1,2,3,4,5,6,6,78,8,90])   ## Vector
print(arr.shape)
reshaped_3 = arr.reshape(2,-1) ## Auto decide the column 
print(reshaped_3.shape)

(10,)
(2, 5)
